
project_id = "kivpijajoxfbkmakykho"

[api]
enabled = true
port = 8000
schemas = ["public", "storage"]

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
enabled = true
port = 8001

[inbucket]
enabled = true
port = 8025
smtp_port = 2500
pop3_port = 1100

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.external.google]
enabled = false

[functions]
enabled = true
port = 9000

[functions.parse-resume]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.match-candidates]
verify_jwt = true

[realtime]
enabled = true
